let startBtn = document.getElementById('start'),
    income = document.getElementsByClassName('budget-value'),
    budgetPerDay = document.getElementsByClassName('daybudget-value'),
    level = document.getElementsByClassName('level-value'),
    expenses = document.getElementsByClassName('expenses-value'),
    optionalExpenses = document.getElementsByClassName('optionalexpenses-value'),
    extraIncome = document.getElementsByClassName('income-value'),
    monthSavings = document.getElementsByClassName('monthsavings-value'),
    yearSavings = document.getElementsByClassName('yearsavings-value'),
    expensesInput = document.getElementsByClassName('expenses-item'),
    optionalExpensesInput = document.querySelectorAll('optionalexpenses-item'),
    possibleIncome = document.querySelector('#count-budget-btn'),
    savingsExist = document.querySelector('#checksavings'),
    savingsExist = document.querySelector('#choose-sum');

